# Generated by Django 2.2.18 on 2023-06-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_num_of_orders',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
