# Generated by Django 2.2.18 on 2023-06-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_max_num_of_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_chat',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.PositiveIntegerField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
