# Generated by Django 2.2.18 on 2023-06-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbo_parser', '0002_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='max_num_of_orders',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
