# Generated by Django 2.2.18 on 2023-06-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbo_parser', '0003_order_max_num_of_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='max_num_of_orders',
        ),
    ]
