# Generated by Django 2.2.18 on 2023-06-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbo_parser', '0004_remove_order_max_num_of_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_link',
            field=models.URLField(max_length=3000),
        ),
    ]
